[tool.pytest.ini_options]
testpaths = "tests/"
log_cli = true
markers = "slow"
addopts = "--durations=0 --strict-markers --doctest-modules"
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
]
